### ISSUE TITLE
Remove ADS mentions and links from this page 

### ISSUE THREAD

**Issue by deansteadman** [NetAppDocs/astra-control-center#101]
Page: [Known issues with Astra Data Store and this Astra Control Center release](https://docs.netapp.com/us-en/astra-control-center/release-notes/known-issues-ads.html)

**Comment by netapp-mwallis** [comment]
Hi Dean,

Thanks for reaching out.  We're working on this according to an internal plan.  Will close this ticket - I believe we're already in communication on this with you via email.

Thanks!
