### ISSUE TITLE
string replacement wrong

### ISSUE THREAD

**Issue by dyangcht** [NetAppDocs/astra-control-center#114]
Page: [Upgrade Astra Control Center](https://docs.netapp.com/us-en/astra-control-center/use/upgrade-acc.html)
At the section "Add the images to your local registry"
The shell script for Podman.  The original script is here
  astraImage=$(podman load --input ${astraImageFile} | sed 's/Loaded image: //')

The string replacement should be "Loaded image(s): " not "Loaded image: ".

**Comment by netapp-mwallis** [comment]
Hi @dyangcht, thanks for bringing this to our attention.  We'll investigate and resolve this issue, and reach out if we have any questions.
Thanks,
Michael

**Comment by netapp-mwallis** [comment]
Hi @dyangcht, what version of podman are you running when you see this output?  Thanks!
--Michael
