### ISSUE TITLE
Found a typo on this page

### ISSUE THREAD

**Issue by JAYAKUMAR-hub** [NetAppDocs/astra-control-center#119]
Page: [Install Astra Control Center using the standard process](https://docs.netapp.com/us-en/astra-control-center/get-started/install_acc.html)

**Comment by JAYAKUMAR-hub** [comment]
Directly edited the file and created pull request

**Comment by amgrissino** [comment]
Thank you for that feedback. I see your pull request and the edits you suggest. We'll just confirm this and get back to you. Appreciate the info!

**Comment by netapp-dbagwell** [comment]
Hi @JAYAKUMAR-hub. 

The original documentation is correct.  The syntax shown is for invoking a kubectl plugin using the kubectl command directly.  The naming of the binary to kubectl-astra complies with kubectl plugin requirements where kubectl-astra should be in the PATH (recommend it be located in same directory as the kubectl executable).  When installed correctly, the “kubectl plugin list” command should show that it found the kubectl-astra plugin.  More info on kubectl plugins here: https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/

If you have more feedback on the docs, please don't hesitate to provide suggestions. Thanks again.
