### ISSUE TITLE
astraImage variable badly built depending on podman version

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetAppDocs/astra-control-center#126]
Page: [Upgrade Astra Control Center](https://docs.netapp.com/us-en/astra-control-center/use/upgrade-acc.html)

Hi,

the _podman load_ command has different outputs depending on the installed version:
- podman3: Loaded image(s): localhost/acc-operator:21.10.19
- podman4: Loaded image: localhost/acc-operator:22.05.99
=> notice the (s) extra with podman3

the consequence is that the script provided by NetApp to push images to a local repo will fail.

The following line needs to be updated to take into account both podman versions:
```
# Load to local cache
  astraImage=$(podman load --input ${astraImageFile} | sed 's/Loaded image(s): //')
```
++

**Comment by amgrissino** [comment]
Thank you for your feedback. We'll look into this and get back to you. Meanwhile, don't hesitate to provide additional feedback.

**Comment by netapp-dbagwell** [comment]
@YvosOnTheHub sorry for the delay on this one. We're still validating some changes to the script and instructions. Thanks again for all your comments on the Astra doc set.

**Comment by netapp-dbagwell** [comment]
Script has been changed to allow for Podman 3 and 4 options. There other improvements to the section as well. Thanks again @YvosOnTheHub. Let us know if you have any more trouble with the content.
