### ISSUE TITLE
Install the updated Astra Control Center operator

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetAppDocs/astra-control-center#127]
Page: [Upgrade Astra Control Center](https://docs.netapp.com/us-en/astra-control-center/use/upgrade-acc.html)

the first step is to run
`cd manifests`

However, the previous chapter may take you to a different directory depending on the method used to push images to the local repo:
- docker: Change to the acc directory extracted from the tar bundle
- podman: You need to be at the root of the tarball

2 possible solutions:
- change the podman procedure to run inside the _acc_ directory
- ask the user to position himself in the _manifests_ directory under the acc folder (without providing the _cd_ command)

++

**Comment by amgrissino** [comment]
Thank you for your feedback. We'll check this out and get back to you. Appreciate it!

**Comment by netapp-dbagwell** [comment]
The section has been updated and includes additional revisions from other commenters from additional requests. "cd manifests" has been removed and replaced with an instruction to go to root of tarball for both processes.
https://docs.netapp.com/us-en/astra-control-center/use/upgrade-acc.html#add-the-images-to-your-local-registry
Closing this issue as done. If you need any more help or clarifications, please reach out. Thanks @YvosOnTheHub.
