### ISSUE TITLE
ACC operator customization

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetAppDocs/astra-control-center#128]
Page: [Upgrade Astra Control Center](https://docs.netapp.com/us-en/astra-control-center/use/upgrade-acc.html)

Hi,

the procedure (2d) states:
```
Add the following values to the env section:
- name: ACCOP_HELM_UPGRADETIMEOUT
  value: 300m
```

As the manifest already has a ACCOP_HELM_INSTALLTIMEOUT variable, the procedure should be:

```
Replace the following values in the env section:
- name: ACCOP_HELM_INSTALLTIMEOUT
  value: 5m

with

- name: ACCOP_HELM_UPGRADETIMEOUT
  value: 300m
```

++

**Comment by amgrissino** [comment]
Thanks again for your feedback. Please continue to send us your comments while we're looking into this.

**Comment by netapp-dbagwell** [comment]
@YvosOnTheHub the ACCOP_HELM_INSTALLTIMEOUT and ACCOP_HELM_UPGRADETIMEOUT are different. No changes needed here. Let me know if you have other comments.

**Comment by YvosOnTheHub** [comment]
ok, so even though you would perform an ACC UPGRADE, you would still need to keep the ACCOP_HELM_INSTALLTIMEOUT parameter?

**Comment by netapp-dbagwell** [comment]
@YvosOnTheHub just confirmed. Correct, there is no need to remove the ACCOP_HELM_INSTALLTIMEOUT parameter during the upgrade.

**Comment by netapp-dbagwell** [comment]
Moving this ticket to closed. If you need additional clarifications, let us know. We're still awaiting feedback on the other two open GH issues. Thanks @YvosOnTheHub.
