### ISSUE TITLE
Use a more K8s-native method to check for Trident version

### ISSUE THREAD

**Issue by wonderland** [NetAppDocs/astra-control-center#129]
Page: [Upgrade Astra Control Center](https://docs.netapp.com/us-en/astra-control-center/use/upgrade-acc.html)

The current doc describes usage of tridentctl to check the version of trident:

"To determine the version you are running, run the following command against your existing Astra Control Center:

../../trident-installer/tridentctl -n trident version"

As not everyone would still have tridentctl around (or be familiar with it), I'd prefer if the docs would use native K8s methods to check. The tridentctl command above can be replaced with

"To determine the version you are running, run the following command against your existing Astra Control Center:

kubectl get tridentversion -n trident"

**Comment by netapp-dbagwell** [comment]
@wonderland thanks. "kubectl get tridentversion -n trident" has replaced the previous command in the live docs.
