### ISSUE TITLE
it is not clear from documentation that there are additional steps to do

### ISSUE THREAD

**Issue by netapp-dgrund** [NetAppDocs/astra-control-center#135]
Page: [Install Astra Control Center using OpenShift OperatorHub](https://docs.netapp.com/us-en/astra-control-center/get-started/acc_operatorhub_install.html)

What's next  -> Next Steps
mention that a route needs to be created for traefik in order to work with ACC

**Comment by netapp-dbagwell** [comment]
Thanks @netapp-dgrund for your feedback. We're working on some updates for this page and will take this point into consideration.

**Comment by netapp-dbagwell** [comment]
@netapp-dgrund the What's Next section has been revised based on your feedback: https://docs.netapp.com/us-en/astra-control-center/get-started/acc_operatorhub_install.html#whats-next
Thanks again.
