### ISSUE TITLE
Please update to Kubernetes version 1.26.

### ISSUE THREAD

**Issue by victorfrancoramos** [NetAppDocs/astra-control-center#145]
Page: [Astra Control Center requirements](https://docs.netapp.com/us-en/astra-control-center/get-started/requirements.html)

**Comment by netapp-mwallis** [comment]
Hi @victorfrancoramos, thanks for your feedback.  The current release of Astra Control Center supports up to Kubernetes version 1.25.  As soon as it supports newer versions, we'll update the documentation.  Let us know if you have any questions.  Thanks!
