### ISSUE TITLE
MySQL deployment links to depreciated/unsupported repository

### ISSUE THREAD

**Issue by tim-ntap** [NetAppDocs/astra-control-center#15]
Page: [Deploy MySQL from a Helm chart](https://docs.netapp.com/us-en/astra-control-center/solutions/mysql-deploy-from-helm-chart.html)

First sentence should probably mention "Learn how to deploy MySQL from the Bitnami Helm chart", rather than "Learn how to deploy MySQL from the standard stable chart." which links to an unsupported repository.

**Comment by netapp-dbagwell** [comment]
Thanks @tim-ntap. I've created an internal ticket for the writer to investigate this.

**Comment by amgrissino** [comment]
We've contacted the subject matter expert for additional input. Will let you know more when we hear.  Thanks, @tim-ntap, for feedback.

**Comment by amgrissino** [comment]
https://docs.netapp.com/us-en/astra-control-center/solutions/mysql-deploy-from-helm-chart.html 
Closing this.
