### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by ntap-johanneswagner** [NetAppDocs/astra-control-center#151]
Page: [Manage remote users and groups](https://docs.netapp.com/us-en/astra-control-center/use/manage-remote-users-groups.html)

We should mention that e-mail is a required field for us and that users, where the email field is empty will not be shown in ACC and can't be used in ACC.
We had now two customers who experienced this and did a lot of troubleshooting to find out that email has to be filled. It seems that some companies don't use this field in their directories and at least in MS ActiveDirectory it is an optional field.

**Comment by netapp-mwallis** [comment]
Thanks for your feedback, @ntap-johanneswagner  - I'll reach out to discuss this issue.  
Thanks, Michael
