### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/astra-control-center#172]
Page: [Install Astra Control Center using the standard process](https://docs.netapp.com/us-en/astra-control-center/get-started/install_acc.html)

The typo `ACC addess` was reported in an accessibility scan. It's on the page three times.

**Comment by amgrissino** [comment]
Thank you @ntap-bmegan for your comments. We will look into this and respond back to you.

**Comment by netapp-dbagwell** [comment]
Good catch and ugh. Corrected in Public repo.
