### ISSUE TITLE
partial URL used in sample is not escaped

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/astra-control-center#173]
Page: [Install Astra Control Center using the standard process](https://docs.netapp.com/us-en/astra-control-center/get-started/install_acc.html)

`In a browser, enter the FQDN ([https://<FQDN>](https://%3Cfqdn%3E/);)`

![image](https://user-images.githubusercontent.com/56453501/232851581-0474ab2a-dbe4-49e8-9597-009451cca23c.png)

**Comment by netapp-dbagwell** [comment]
Thanks Megan. We'll fix this.

**Comment by netapp-dbagwell** [comment]
This issue is corrected in public repo. We have another issue going to standardize our parentheses style.

**Comment by ntap-bmegan** [comment]
The parens aren't the problem. The unescaped `https` is the problem.

**Comment by netapp-dbagwell** [comment]
Changed wording to avoid the problematic construction: https://docs.netapp.com/us-en/astra-control-center/get-started/install_acc.html#log-in-to-the-astra-control-center-ui
