### ISSUE TITLE
ACC doc link to generate NLF is circular, pointing back to same page.

### ISSUE THREAD

**Issue by crossond** [NetAppDocs/astra-control-center#174]
Page: [Licensing](https://docs.netapp.com/us-en/astra-control-center/concepts/licensing.html)

- This link is circular, pointing back to this same page, instead of a page for instructions or help to obtain the NLF.

[If you already purchased Astra Control Center, generate your NetApp license file (NLF)](https://docs.netapp.com/us-en/astra-control-center/concepts/licensing.html) from the NetApp Support Site. After you purchase the product, you receive a serial number and license, which you use on the Support Site.

**Comment by netapp-mwallis** [comment]
Thanks for letting us know about this incorrect link, @crossond - we're working on fixing this now.  Will update here when we're done.
