### ISSUE TITLE
checkboxes are not supported for docs.netapp.com

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/astra-control-center#188]
### Page URL

https://docs.netapp.com/us-en/astra-control-center/get-started/quick-start.html

### Page title

Quick start for Astra Control Center

### Summary

The state of the check is not persistent, creating a usability problem, so they are prohibited. 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
Thanks @ntap-bmegan. Check boxes changed to bullet points: https://docs.netapp.com/us-en/astra-control-center/get-started/quick-start.html
