### ISSUE TITLE
Creating custom kubeconfig procedure is no longer valid with Kubernetes 1.24+

### ISSUE THREAD

**Issue by luisrico** [NetAppDocs/astra-control-center#189]
### Page URL

https://docs.netapp.com/us-en/astra-control-center/get-started/setup_overview.html

### Page title

Set up Astra Control Center

### Summary

URGENT! 
Creating custom kubeconfig procedure is no longer valid with Kubernetes 1.24+ because ServiceAccounts are not created with Token Secret. There are 2 additional steps to be added here before step #4: 
- Creating token secret:
```
cat <<EOF > secret-astracontrol-service-account.yaml
apiVersion: v1
kind: Secret
metadata:
  name: secret-astracontrol-service-account
  annotations:
    kubernetes.io/service-account.name: "astracontrol-service-account"
type: kubernetes.io/service-account-token
EOF
```

`kubectl apply -f secret-astracontrol-service-account.yaml`

- Adding secret to Service Account:
`kubectl edit sa astracontrol-service-account`

```
apiVersion: v1
imagePullSecrets:
- name: astracontrol-service-account-dockercfg-48xhx
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"astracontrol-service-account","namespace":"default"}}
  creationTimestamp: "2023-06-14T15:25:45Z"
  name: astracontrol-service-account
  namespace: default
  resourceVersion: "2767069"
  uid: 2ce068c4-810e-4a96-ada3-49cbf9ec3f89
secrets:
- name: astracontrol-service-account-dockercfg-48xhx
- name: secret-astracontrol-service-account      <----- Add this line when editing, then TOKEN INDEX = 1

```

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-mwallis** [comment]
Hi @luisrico, thanks for catching this.  We are tracking this here as well as in https://jira.ngage.netapp.com/browse/ASTRADOC-157 which was already an open issue, but thank you for the steps to generate the secret - I'm working on adding these to the doc now.

**Comment by luisrico** [comment]
Thanks Michael!
It would be great if somebody from engineering could review my steps...

**Comment by netapp-mwallis** [comment]
Hi @luisrico , this is still in review / correction with engineering, and we hope to finalize the changes soon.

**Comment by netapp-dbagwell** [comment]
@luisrico, this change is going in as part of larger revision to this section. We're still working with engineering to test environments/scenarios. We'll update you when the changes post to public.

**Comment by netapp-dbagwell** [comment]
@luisrico these requested changes are live with the 23.07 release: https://docs.netapp.com/us-en/astra-control-center/get-started/setup_overview.html#create-a-cluster-role-kubeconfig
