### ISSUE TITLE
FSxN & Metrocluster

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetAppDocs/astra-control-center#195]
### Page URL

https://docs.netapp.com/us-en/astra-control-center/get-started/requirements.html

### Page title

Astra Control Center requirements

### Summary

Hi, 

Metrocluster is a datacenter architecture, hence not feasible with FSxN
Maybe the FSxN example link should be removed from this paragraph in order to avoid confusion

++ 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-mwallis** [comment]
Hi @YvosOnTheHub, thanks for catching this.  I'm investigating internally and will reply when I have more info. 
Thanks,
Michael
