### ISSUE TITLE
Minimal origin version

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetAppDocs/astra-control-center#199]
### Page URL

https://docs.netapp.com/us-en/astra-control-center/use/upgrade-acc.html

### Page title

Upgrade Astra Control Center

### Summary

Hi
this page tells us the steps to upgrade to the latest ACC version.
However, it does not say what is the minimal version from which we can upgrade.... (any? 22.11? 23.04? etc...)
that would be valuable information to have
thanks

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
Hi @YvosOnTheHub. I'll ask if there are any limitations from previous versions. Closing this GitHub issue here. I'll add you on the internal issue I open.
