### ISSUE TITLE
Link  goes nowhere

### ISSUE THREAD

**Issue by NA-Scott** [NetAppDocs/astra-control-center#202]
### Page URL

https://docs.netapp.com/us-en/astra-control-center/get-started/quick-start.html

### Page title

Quick start for Astra Control Center

### Summary

This link doesn't exist:
[Configure Astra Trident storage backend](https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-postdeployment.html#step-1-create-a-backend)

That's the 3rd bullet under storage integration

I'm guessing it should go to https://docs.netapp.com/us-en/trident/trident-use/backends.html

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-mwallis** [comment]
Thanks for catching this @NA-Scott - we'll fix this link issue shortly.
