### ISSUE TITLE
Document requirement to have unique SVM name

### ISSUE THREAD

**Issue by CDS2023-storageworkshop** [NetAppDocs/astra-control-center#204]
### Page URL

https://docs.netapp.com/us-en/astra-control-center/use/replicate_snapmirror.html

### Page title

Replicate apps between storage backends using SnapMirror technology

### Summary

ACC replication between two Ontap systems only works when the SVM names are unique. While requiring special configuration in form of a "local name", Ontap allows to peer SVMs that have identical names. However this setup does not work with ACC. 

Can we please add a note on this to the "Replication prerequisites --> Peering --> Cluster and SVM" section?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
@CDS2023-storageworkshop thanks for feedback! We'll look into making your requested changes and keep you updated in this issue.

**Comment by netapp-dbagwell** [comment]
@CDS2023-storageworkshop a note has been added to the documentation: https://docs.netapp.com/us-en/astra-control-center/use/replicate_snapmirror.html
