### ISSUE TITLE
Configure ACC steps for v23.07 and v23.10 ACC :  > 'additionalValues' shows 'polaris-keycloak',  should be 'keycloak-operator'

### ISSUE THREAD

**Issue by crossond** [NetAppDocs/astra-control-center#212]
### Page URL

https://docs.netapp.com/us-en/astra-control-center/get-started/install_acc.html#configure-astra-control-center

### Page title

Configure Astra Control Center

### Summary

Per Dave Dow, "**polaris-keycloak**" should be "**keycloak-operator**".  

Configure ACC steps for v23.07 and v23.10 ACC :  > 'additionalValues' shows 'polaris-keycloak',  should be 'keycloak-operator'

**For 23.07 and 23.10 doc versions:**

> additionalValues

additionalValues:
    polaris-keycloak:     <----------- this should be 'keycloak-operator'
      livenessProbe:
        initialDelaySeconds: 180
      readinessProbe:
        initialDelaySeconds: 180

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
@crossond thanks. Following up with the author of that particular workaround.

**Comment by netapp-dbagwell** [comment]
Updated as part of https://github.com/NetAppDocs/astra-control-center/pull/217/files. Thanks again for your feedback.
