### ISSUE TITLE
TASR example in step1 missing information

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetAppDocs/astra-control-center#216]
### Page URL

https://docs.netapp.com/us-en/astra-control-center/use-acp/acp-snap-restore.html

### Page title

Recover volume data using a snapshot

### Summary

Hi

in order to work, the TASR should be configured with 
=> apiVersion: trident.netapp.io/v1
documentation shows 
=> apiVersion: v1

this must be changed in both _step1_ & _results_ chapters

++

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
Thanks @YvosOnTheHub! We'll take a look at this and keep you posted about the update. Appreciate the feedback.

**Comment by juliantap** [comment]
Adding @clintonk to confirm we need to update TASR CR command to: `apiVersion: trident.netapp.io/v1`

**Comment by YvosOnTheHub** [comment]
if we declare the resource with only "v1", we get the following error message:
```
error: resource mapping not found for name: "mydatarestore" namespace: "sc06busybox" from "resto.yaml": no matches for kind "TridentActionSnapshotRestore" in version "v1"
ensure CRDs are installed first
```
