### ISSUE TITLE
ACC DRP & Trident backend

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetAppDocs/astra-control-center#223]
### Page URL

https://docs.netapp.com/us-en/astra-control-center/use/replicate_snapmirror.html

### Page title

Replicate apps between storage backends using SnapMirror technology

### Summary

Hi

there is one critical information missing from this page:
which trident drivers are supported...
that would be helpful to have it in 2 places:
- on each feature's page
- a summary page that lists all the features with the corresponding trident drivers supported

++

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-mwallis** [comment]
Hi @YvosOnTheHub - thanks for pointing this out.  We'll address this issue in the JIRA ticket https://jira.ngage.netapp.com/browse/ASTRADOC-363 and update here when complete.
