### ISSUE TITLE
Incomplete table on network requirements

### ISSUE THREAD

**Issue by wonderland** [NetAppDocs/astra-control-center#224]
### Page URL

https://docs.netapp.com/us-en/astra-control-center/get-started/requirements.html

### Page title

Astra Control Center requirements

### Summary

https://docs.netapp.com/us-en/astra-control-center/get-started/requirements.html#networking-requirements

The first line in the table reads "UI / API access - Ensure this port is open both ways between the cluster hosting Astra Control Center and each managed cluster". This seems to be correct for the UI/API access part. But the rest of that sentence is not correct for Client PC to Astra communication. It instead describe the communication between Astra and each managed cluster. Which is very important but currently missing from that table. 

There should be an additonal line in the Table:
Source: Astra Control Center
Destination: Managed Kubernetes Cluster
Port: 443/6443
Protocol: HTTPS
Purpose: Ensure this port is open both ways between the cluster hosting Astra Control Center and each managed cluster

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-mwallis** [comment]
Tracking this improvement under https://jira.ngage.netapp.com/browse/ASTRADOC-384.
