### ISSUE TITLE
inconsistencies in the TechPreview connector paragraph

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetAppDocs/astra-control-center#240]
### Page URL

https://docs.netapp.com/us-en/astra-control-center/use/manage-buckets.html

### Page title

Manage buckets

### Summary

Hi,

some errors or things to change:
- AppVault YAML example: name: astra_appvault => the name cannot contain "_" but can contain "-"

- Ensure the bucket is one of the following types: NetApp ONTAP S3 / NetApp StorageGRID S3 / Microsoft Azure / Generic S3
=> but then "Amazon Web Services (AWS) and **Google Cloud Platform (GCP)** use the Generic S3 bucket type."

- kubectl apply -f astra_appvault.yaml -n neptune-system
=> there is not explanation anywhere about the **neptune-system** namespace. is it correct or should it be **astra-connector**?

- bucket access keys & secrets
=> provide examples on how to create those secrets

- spec.providerCredentials: (Optional) 
=> why is it optional ? because of the "secure" parameter? which defaults to what?

- spec.providerType: (Required) Determines what provides the backup; for example, **S3 or FileSystem**.
=> "FileSystem"?
Shouldn't it be one of the following?
"ontap-s3" / "storagegrid-s3" / "generic-s3" / "gcp" / "azure" / "aws"

++

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
@YvosOnTheHub we'll handle the tracking of this one internally and add you as watcher for the issue. Closing this external GH request.
