### ISSUE TITLE
Create Kubeconfig script has an error

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetAppDocs/astra-control-center#34]
Page: [Prerequisites for adding a cluster](https://docs.netapp.com/us-en/astra-control-center/get-started/add-cluster-reqs.html)

The beginning of the create-kubeconfig.sh script looks like:
SECRET_NAME=$(kubectl get serviceaccount ${SERVICE_ACCOUNT_NAME} \
  --context ${CONTEXT} \
  --namespace ${NAMESPACE} \
  -o jsonpath='{.secrets[**TOKEN_INDEX**].name}')

However, this cannot work as it will not use the TOKEN_INDEX parameter value, since there are some characters missing, "$", etc...

**Comment by netapp-dbagwell** [comment]
Thanks for the feedback, @YvosOnTheHub. I've opened an internal ticket to address this. We'll let you know when there's an update.

**Comment by netapp-mwallis** [comment]
Hi @YvosOnTheHub, we've revised the script and instructions surrounding it - this is no longer a variable, but is something you must change to a static value in the script before you run it.  Can you check the following link and let us know your thoughts?  If you approve, we'll make the change public.
Thanks!
https://review.docs.netapp.com/us-en/astra-control-center_mw-hotfix-doc-3933/get-started/add-cluster-reqs.html#create-an-admin-role-kubeconfig

**Comment by YvosOnTheHub** [comment]
it is indeed much clearer now!
thank you for taking this into account
