### ISSUE TITLE
Terminology changes

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/astra-control-center#65]
Page: [Install Astra Control Center with a Cloud Volumes ONTAP storage backend](https://docs.netapp.com/us-en/astra-control-center/get-started/install_acc-cvo.html)

1. "Cloud Volumes ONTAP connector" should be "Cloud Manager Connector"
2. "CVO" should be "Cloud Volumes ONTAP"
3. In the Azure section, "virtual private cloud" should be "virtual network"
4. "Azure Blob S3 bucket" should be "Azure Blob container"

**Comment by netapp-dbagwell** [comment]
Thanks @netapp-bcammett! We'll get these fixes in today.

**Comment by netapp-dbagwell** [comment]
Hi @netapp-bcammett! Changes from https://github.com/NetAppDocs/astra-control-center/pull/66 are now live.
https://docs.netapp.com/us-en/astra-control-center/get-started/install_acc-cvo.html
