### ISSUE TITLE
Spelling Error in Architecture Diagram

### ISSUE THREAD

**Issue by andrewhatfield** [NetAppDocs/astra-control-center#7]
Page: [Architecture and components](https://docs.netapp.com/us-en/astra-control-center/concepts/architecture.html)

The [architecture diagram](https://docs.netapp.com/us-en/astra-control-center/media/concepts/astra-cc-arch.png) says "Customer Premise" when it should say "Customer Premises"

**Comment by amgrissino** [comment]
Thank you for that catch! We will update the diagram.

**Comment by andrewhatfield** [comment]
No worries, thanks for following up!

**Comment by amgrissino** [comment]
Updated the diagram in the internal review branch. Will go out in next update to site soon.

**Comment by amgrissino** [comment]
Closing this. 
Thanks again @andrewhatfield! 

https://docs.netapp.com/us-en/astra-control-center/concepts/architecture.html
