### ISSUE TITLE
Steps for Nginx ingress controller - deprecation version

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetAppDocs/astra-control-center#76]
Page: [Install Astra Control Center using the standard process](https://docs.netapp.com/us-en/astra-control-center/get-started/install_acc.html)

Hi

this page displays the following:

> Deploy an ingress resource in netapp-acc (or custom-named) namespace using either the vibeta1 (**deprecated in Kubernetes version less than or 1.22**) or v1 resource type for either a deprecated or a new schema

this does not make sense, v1beta1 (& not vibeta1) has been deprecated in 1.22, so v1 should be used for versions 1.22 & above
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122

++

**Comment by netapp-dbagwell** [comment]
@YvosOnTheHub thanks for the catch. We'll address that shortly.

**Comment by amgrissino** [comment]
@YvosOnTheHub  - We're updating this topic with the change. Thank you again! 
https://docs.netapp.com/us-en/astra-control-center/get-started/install_acc.html

**Comment by amgrissino** [comment]
Closing this.
