### ISSUE TITLE
Docker registry now requires authentication

### ISSUE THREAD

**Issue by obassett** [NetAppDocs/astra-control-center#84]
Page: [Manage repository connections](https://docs.netapp.com/us-en/astra-control-center/use/manage-connections.html)

Astra Control Center now requires authentication when adding a docker registry - there is no longer an authentication check-box just a registry box, optional repository box, and username and password fields.

**Comment by obassett** [comment]
HI @netapp-dbagwell 

I am running: 22.05.341-manual-AVP-EAP-22-05-385af6ed0-29

It was also the same in 22.04 though.

Thanks

**Comment by netapp-mwallis** [comment]
Hi @obassett - we've made the documentation change to reflect this properly now. Thanks for making us aware of the issue. Have a great day!
--Michael
