### ISSUE TITLE
ACC docs are missing a requirement.

### ISSUE THREAD

**Issue by NA-Scott** [NetAppDocs/astra-control-center#9]
Page: [Astra Control Center requirements](https://docs.netapp.com/us-en/astra-control-center/get-started/requirements.html)

Line 21 should read:
* *Trident / ONTAP storage configuration*: Astra Control Center requires that Trident version 21.01 or 21.04 already be installed and configured to work with NetApp ONTAP version 9.5 or newer as the storage backend. Astra Control Center requires that the storage class be created and set as the default storage class. Astra Control Center supports the following ONTAP drivers provided by Trident:

**Comment by amgrissino** [comment]
Thank you, @NA-Scott. We will review the information with Engineering and get back to you.

**Comment by amgrissino** [comment]
Update: We're discussing some additional changes and you are on that thread, @NA-Scott.

**Comment by netapp-mwallis** [comment]
Hi @NA-Scott, we've added the sentence you requested in the requirements. We also have some additional information below this paragraph in the same topic that addresses folks that want to host ACC from a managed cluster.  You can view the draft content here: 
https://review.docs.netapp.com/us-en/astra-control-center_acc_mw_hotfix_doc-3719/get-started/requirements.html#kubernetes-cluster-general-requirements
If this looks good, please let us know and we'll make this change live.  Thanks!

**Comment by NA-Scott** [comment]
Looks good.


--Scott

**Comment by netapp-mwallis** [comment]
Changes are now live.  Thanks!
