### ISSUE TITLE
An addition to Replication Pre-requisites

### ISSUE THREAD

**Issue by DianePatton** [NetAppDocs/astra-control-center#91]
Page: [Astra Control Center requirements](https://docs.netapp.com/us-en/astra-control-center/get-started/requirements.html)

One additional pre-req needs to be added to the Replication Pre-Requisites. Feel free to re-word.

- The user entered to manage the ONTAP backends from ACC must have the user login access methods  _http_ and _ontapi_ enabled within ONTAP System Manager on both ONTAP clusters. See [Manage User Accounts](https://docs.netapp.com/us-en/ontap-sm-classic/online-help-96-97/concept_cluster_user_accounts.html#users-list) for more information.

**Comment by amgrissino** [comment]
Thank you, @DianePatton. We'll work with Eng on this info.

**Comment by netapp-mwallis** [comment]
@DianePatton  "The user entered" - is this user entered in an ONTAP UI?  And they would have to enter it on both clusters?

**Comment by netapp-mwallis** [comment]
DOC-4460 is complete - marking this as done.
