### ISSUE TITLE
Need to update ACC resource requirements (for self managing ACC K8s cluster)

### ISSUE THREAD

**Issue by rarvind33** [NetAppDocs/astra-control-center#99]
Page: [Astra Control Center requirements](https://docs.netapp.com/us-en/astra-control-center/get-started/requirements.html)

As per this documentation, the current resource requirements on the worker nodes are 4 CPUs and 12 GB RAM. 
I have run into resource constraints on the plain vanilla upstream K8s cluster v1.23.10 with these resources while using ACC 22.08.0. 
Since the recommendation is to manage the K8s cluster on which ACC is deployed, we will also need to account for the resources that will be needed to deploy the netapp-monitoring related objects.

root@master-01:~# k get events -n netapp-monitoring
LAST SEEN   TYPE      REASON             OBJECT                    MESSAGE
3m48s       Warning   BackOff            pod/fluent-bit-ds-4n4vw   Back-off restarting failed container
3m59s       Warning   FailedScheduling   pod/fluent-bit-ds-frw9h   0/4 nodes are available: 1 Insufficient memory, 3 node(s) didn't match Pod's node affinity/selector.
3m29s       Warning   FailedScheduling   pod/telegraf-ds-dqv67     0/4 nodes are available: 1 Insufficient cpu, 1 Insufficient memory, 3 node(s) didn't match Pod's node affinity/selector.

We will need to update these values to minimums that also factor the netapp-monitoring resource requirements.

**Comment by netapp-mwallis** [comment]
Hi @rarvind33, thanks for bringing this to our attention.  I'll reach out to discuss specifics.

**Comment by netapp-mwallis** [comment]
Per PM, this documentation will be updated for PI-7.  Tracking with an internal ticket; closing this out and will resume work in the ticket.
